### ISSUE TITLE
[QUESTION]: Aurora with PostgreSQL compatibility option

### ISSUE THREAD

**Issue by scheung38** [Rayraegah/terraform-aws-hasura#16]
Will this work with Aurora as mentioned in title instead of normal PostgreSQL

**Comment by Rayraegah** [comment]
Hasura GraphQL engine supports Postgres 9.5 and above. This terraform script is written for RDS Postgres w/ Fargate and I don't plan to support Aurora terraform in this script.

However, Hasura can work with Aurora Postgres. You'll find [examples](https://github.com/hasura/hasura-aws-stack) in the wild for such integrations.
