### ISSUE TITLE
Update variables in readme for v3.0.0

### ISSUE THREAD

**Issue by Rayraegah** [Rayraegah/terraform-aws-hasura#19]
New variables have been introduced in v3.0.0 and these are not documented for terraform registry https://registry.terraform.io/modules/Rayraegah/hasura/aws/3.0.0

**Comment by pharindoko** [comment]
Use terraform-docs:
https://github.com/segmentio/terraform-docs

 => with a special replace command in readme
https://github.com/cytopia/docker-terraform-docs#replace-in-readmemd
