### ISSUE TITLE
[Question] Costs for deployment

### ISSUE THREAD

**Issue by Destreyf** [Rayraegah/terraform-aws-hasura#24]
I was looking into a similar approach and ran across your terraform module.

I was wondering if you had a rough idea of costs for a starting deployment, just assuming the bare minimums are running from this terraform.

**Comment by Destreyf** [comment]
To clarify, i'm just wondering what the costs on AWS are for the services running

**Comment by Rayraegah** [comment]
Terraform has a [cost estimate feature](https://www.terraform.io/docs/cloud/cost-estimation/aws.html) and these resources incur cost

- aws_alb
- aws_autoscaling_group
- aws_cloudwatch_dashboard
- aws_cloudwatch_metric_alarm
- aws_db_instance
- aws_dynamodb_table
- aws_ebs_volume
- aws_elasticache_cluster
- aws_elasticsearch_domain
- aws_elb
- aws_instance
- aws_lb
- aws_rds_cluster

This module [defines 27 resources](https://registry.terraform.io/modules/Rayraegah/hasura/aws/3.0.2?tab=resources) and here are some of the ones that incur cost. When using this module, it may create less resources if you use a submodule.

- aws_alb.hasura
- aws_db_instance.hasura
- aws_ecs_cluster.hasura
- aws_ecs_service.hasura

You can head over to [AWS cost calculator](https://calculator.aws/#/addService) and use the default settings on the above resources to determine the cost. Alternatively you can use the [terraform-cost-estimation module](https://github.com/antonbabenko/terraform-cost-estimation) from `curl` do get a rough estimate on the infrastructure cost of this module.

**Comment by Destreyf** [comment]
@Rayraegah Thank you for such a detailed answer on how to do this,  i did run across the terraform cost estimate feature, but it requires you pay for the cloud service to use.

I'll look into using the terraform-cost-estimation module, i'm new to terraform and am excited to learn more about it and try to implement it for my deployments.
