### ISSUE TITLE
Publish to Terraform Registry

### ISSUE THREAD

**Issue by davetapley** [Rayraegah/terraform-aws-hasura#6]
Hey @Rayraegah, do you have any objections to publishing this to the [Terraform Registry](https://registry.terraform.io/)?

Looks like it's just a few button clicks, since you've already tagged v2.0 👌

**Comment by Rayraegah** [comment]
I don't mind publishing it. Just never done it before. Let me read up on it and get that started.

**Comment by Rayraegah** [comment]
renamed project from `hasura-aws` to [`terraform-aws-hasura`](https://www.terraform.io/docs/registry/modules/publish.html) to comply with publishing standards.

now available on terraform modules registry 🎉https://registry.terraform.io/modules/Rayraegah/hasura/aws/2.0.0
